<?php

namespace Database\Seeders;

use App\Models\Property;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $agents = \App\Models\Agent::all();
        $projects = \App\Models\Project::all();

        $properties = [
            [
                'name' => 'شقة فاخرة بإطلالة بحرية',
                'slug' => 'luxury-sea-view-apartment',
                'description' => 'شقة فاخرة من 3 غرف نوم وصالة في برج حديث مع إطلالة بانورامية على البحر. تشطيبات راقية، مطبخ مجهز بالكامل، وشرفة واسعة. يوفر المبنى مسبح، صالة رياضية، وأمن 24 ساعة.',
                'status' => true,
                'is_featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => true,
                'categories' => ['apartment', 'penthouse'],
                'city' => 'دبي',
                'state' => 'إمارة دبي',
                'price' => 1850000,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'space' => 2200,
                'project_id' => $projects[0]->id ?? null,
                'agent_id' => $agents[0]->id ?? null,
            ],
            [
                'name' => 'فيلا عصرية في مجمع راقي',
                'slug' => 'modern-villa-luxury-compound',
                'description' => 'فيلا مستقلة بتصميم عصري في مجمع سكني مغلق. 5 غرف نوم رئيسية، حديقة خاصة، مسبح، ومواقف لسيارتين. موقع هادئ وآمن مع مرافق ترفيهية متكاملة.',
                'status' => true,
                'is_featured' => true,
                'is_for_rent' => false,
                'is_for_sale' => true,
                'categories' => ['villa', 'luxury'],
                'city' => 'أبوظبي',
                'state' => 'إمارة أبوظبي',
                'price' => 4500000,
                'bedrooms' => 5,
                'bathrooms' => 6,
                'space' => 4800,
                'project_id' => $projects[1]->id ?? null,
                'agent_id' => $agents[1]->id ?? null,
            ],
            [
                'name' => 'مكتب تجاري في برج حديث',
                'slug' => 'commercial-office-modern-tower',
                'description' => 'مكتب تجاري واسع في برج الأعمال الرئيسي. مساحة مفتوحة قابلة للتخصيص، إطلالات مميزة، وموقع استراتيجي. يشمل مواقف سيارات وخدمات صيانة.',
                'status' => true,
                'is_featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'categories' => ['office', 'commercial'],
                'city' => 'الرياض',
                'state' => 'منطقة الرياض',
                'price' => 350000,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'space' => 850,
                'project_id' => $projects[2]->id ?? null,
                'agent_id' => $agents[2]->id ?? null,
            ],
            [
                'name' => 'شاليه على البحر مباشرة',
                'slug' => 'beachfront-chalet',
                'description' => 'شاليه فاخر على الشاطئ مباشرة مع حديقة خاصة. 4 غرف نوم، صالة واسعة، ومطبخ عصري. إطلالة ساحرة ومثالي للعائلات. خدمات فندقية متوفرة.',
                'status' => true,
                'is_featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => true,
                'categories' => ['villa', 'townhouse'],
                'city' => 'جدة',
                'state' => 'منطقة مكة المكرمة',
                'price' => 2800000,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'space' => 3500,
                'project_id' => $projects[3]->id ?? null,
                'agent_id' => $agents[3]->id ?? null,
            ],
            [
                'name' => 'منزل عائلي واسع',
                'slug' => 'spacious-family-house',
                'description' => 'منزل عائلي مريح في حي هادئ. 4 غرف نوم، مجلس، صالة طعام، وحديقة خلفية. قريب من المدارس والمراكز التجارية. مثالي للعائلات الكبيرة.',
                'status' => true,
                'is_featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => true,
                'categories' => ['house', 'townhouse'],
                'city' => 'الشارقة',
                'state' => 'إمارة الشارقة',
                'price' => 1200000,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'space' => 2800,
                'project_id' => $projects[4]->id ?? null,
                'agent_id' => $agents[4]->id ?? null,
            ],
            [
                'name' => 'محل تجاري في موقع حيوي',
                'slug' => 'commercial-shop-prime-location',
                'description' => 'محل تجاري بمساحة ممتازة في منطقة حيوية. واجهة زجاجية عصرية، موقف سيارات، ومرافق خدمية. مناسب لجميع الأنشطة التجارية.',
                'status' => true,
                'is_featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'categories' => ['retail', 'commercial'],
                'city' => 'الدوحة',
                'state' => 'قطر',
                'price' => 180000,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'space' => 450,
                'project_id' => $projects[5]->id ?? null,
                'agent_id' => $agents[5]->id ?? null,
            ],
            [
                'name' => 'شقة استوديو حديثة',
                'slug' => 'modern-studio-apartment',
                'description' => 'استوديو عصري مفروش بالكامل في موقع مركزي. تصميم ذكي يوفر الراحة والعملية. مثالي للشباب والمهنيين. يشمل موقف سيارة ومرافق مشتركة.',
                'status' => true,
                'is_featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'categories' => ['studio', 'apartment'],
                'city' => 'عجمان',
                'state' => 'إمارة عجمان',
                'price' => 45000,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'space' => 520,
                'project_id' => $projects[6]->id ?? null,
                'agent_id' => $agents[6]->id ?? null,
            ],
            [
                'name' => 'مستودع للإيجار',
                'slug' => 'warehouse-for-rent',
                'description' => 'مستودع واسع بمواصفات عالية في المنطقة الصناعية. مساحة تخزين كبيرة، منطقة تحميل، ومكاتب إدارية. أمن وحراسة 24 ساعة.',
                'status' => true,
                'is_featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'categories' => ['warehouse', 'commercial'],
                'city' => 'المنامة',
                'state' => 'البحرين',
                'price' => 120000,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'space' => 1200,
                'project_id' => $projects[7]->id ?? null,
                'agent_id' => $agents[7]->id ?? null,
            ],
            [
                'name' => 'دوبلكس فاخر في برج جديد',
                'slug' => 'luxury-duplex-new-tower',
                'description' => 'دوبلكس فاخر على طابقين في برج حديث. 4 غرف نوم، صالتين، ومطبخ إيطالي. تشطيبات فاخرة وإطلالات بانورامية. يوفر البرج مرافق VIP.',
                'status' => true,
                'is_featured' => true,
                'is_for_rent' => false,
                'is_for_sale' => true,
                'categories' => ['duplex', 'penthouse', 'apartment'],
                'city' => 'العين',
                'state' => 'إمارة أبوظبي',
                'price' => 2200000,
                'bedrooms' => 4,
                'bathrooms' => 5,
                'space' => 3200,
                'project_id' => $projects[8]->id ?? null,
                'agent_id' => $agents[8]->id ?? null,
            ],
            [
                'name' => 'أرض سكنية في موقع مميز',
                'slug' => 'residential-land-prime-location',
                'description' => 'أرض سكنية بمساحة كبيرة في موقع استراتيجي. مناسبة للبناء السكني أو الاستثماري. تراخيص بناء جاهزة وخدمات متوفرة (كهرباء، ماء، صرف صحي).',
                'status' => true,
                'is_featured' => true,
                'is_for_rent' => false,
                'is_for_sale' => true,
                'categories' => ['land'],
                'city' => 'الكويت',
                'state' => 'دولة الكويت',
                'price' => 950000,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'space' => 1800,
                'project_id' => $projects[9]->id ?? null,
                'agent_id' => $agents[9]->id ?? null,
            ],
        ];

        foreach ($properties as $property) {
            Property::create($property);
        }
    }
}
